---
title: "TBD"
author: 'TBD)'
date: "10/10/2020"
output: pdf_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(readr)
library(tinytex)
library(ggplot2)
gss <- read_csv("gss.csv")
```

## Abstract
## Introduction
## Data

## Model
## Results
## Discussion

## References
H. Wickham. ggplot2: Elegant Graphics for Data Analysis. Springer-Verlag New York, 2016.

Hadley Wickham, Jim Hester and Romain Francois (2018). readr: Read Rectangular Text Data. R package version 1.3.1.
  https://CRAN.R-project.org/package=readr

JJ Allaire and Yihui Xie and Jonathan McPherson and Javier Luraschi and Kevin Ushey and Aron Atkins and Hadley
  Wickham and Joe Cheng and Winston Chang and Richard Iannone (2020). rmarkdown: Dynamic Documents for R. R package
  version 2.3. URL https://rmarkdown.rstudio.com.
  
 R Core Team (2020). R: A language and environment for statistical computing. R Foundation for Statistical
  Computing, Vienna, Austria. URL https://www.R-project.org/.
  
Rohan Alexander and Sam Caetano (2020). GSS cleaning. University of Toronto, rohan.alexander@utoronto.ca

Wickham et al., (2019). Welcome to the tidyverse. Journal of Open Source Software, 4(43), 1686,
  https://doi.org/10.21105/joss.01686
  
Yihui Xie (2020). tinytex: Helper Functions to Install and Maintain TeX Live, and Compile LaTeX Documents. R
  package version 0.26.
  
Yihui Xie and J.J. Allaire and Garrett Grolemund (2018). R Markdown: The Definitive Guide. Chapman and Hall/CRC.
  ISBN 9781138359338. URL https://bookdown.org/yihui/rmarkdown.
  
Yihui Xie (2019) TinyTeX: A lightweight, cross-platform, and easy-to-maintain LaTeX distribution based on TeX
  Live. TUGboat 40 (1): 30--32. http://tug.org/TUGboat/Contents/contents40-1.htm

